In [1]:
import json
import pandas as pd
import numpy as np

import re

from sqlalchemy import create_engine
import psycopg2

from config import db_password

import time

In [2]:
#  Add the clean movie function that takes in the argument, "movie".
def clean_movie(movie):

    movie = dict(movie) # create a non-destructive copy
    alt_titles = {}
    for key in ['Also known as', 'Arabic', 'Cantonese', 'Chinese', 'French', 
                'Hangul', 'Hebrew', 'Hepburn', 'Japenese', 'Literally', 
                'Mandarin', 'McCune-Reischauer', 'Original title', 'Polish',
                'Revised Romanization', 'Romanized', 'Russian',
                'Simplified', 'Traditional', 'Yiddish']:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles
         # merge column names
    def change_column_name(old_name, new_name):
        if old_name in movie:
            movie[new_name] = movie.pop(old_name)
    change_column_name('Adaptation by', 'Writer(s)')
    change_column_name('Country of origin', 'Country')
    change_column_name('Directed by', 'Director')
    change_column_name('Distributed by', 'Distributor')
    change_column_name('Edited by', 'Editor(s)')
    change_column_name('Length', 'Running time')
    change_column_name('Original release', 'Release date')
    change_column_name('Music by', 'Composer(s)')
    change_column_name('Produced by', 'Producer(s)')
    change_column_name('Producer', 'Producer(s)')
    change_column_name('Productioncompanies ', 'Production company(s)')
    change_column_name('Productioncompany ', 'Production company(s)')
    change_column_name('Released', 'Release date')
    change_column_name('Release Date', 'Release date')
    change_column_name('Screen story by', 'Writer(s)')
    change_column_name('Screenplay by', 'Writer(s)')
    change_column_name('Story by', 'Writer(s)')
    change_column_name('Theme music composer', 'Composer(s)')
    change_column_name('Written by', 'Writer(s)')
    
    
    return movie

In [3]:
# 1 Add the function that takes in three arguments;
# Wikipedia data, Kaggle metadata, and MovieLens rating data (from Kaggle)

def extract_transform_load(wiki_file, kaggle_file, ratings_file):
    # Read in the kaggle metadata and MovieLens ratings CSV files as Pandas DataFrames.
    kaggle_metadata = pd.read_csv(kaggle_file, low_memory=False)
    ratings = pd.read_csv(ratings_file)

    # Open and read the Wikipedia data JSON file.
    with open(wiki_file, mode='r') as file:
        wiki_movies_raw = json.load(file)
    
    # Write a list comprehension to filter out TV shows.
    wiki_movies = [movie for movie in wiki_movies_raw
               if ('Director' in movie or 'Directed by' in movie) 
               and 'imdb_link' in movie
               and 'No. of episodes' not in movie]

    # Write a list comprehension to iterate through the cleaned wiki movies list
    # and call the clean_movie function on each movie.
    clean_movies = [clean_movie(movie) for movie in wiki_movies]

    # Read in the cleaned movies list from Step 4 as a DataFrame.
    wiki_movies_df = pd.DataFrame(clean_movies)

    # Write a try-except block to catch errors while extracting the IMDb ID using a regular expression string and
    #  dropping any imdb_id duplicates. If there is an error, capture and print the exception.
    try:
        wiki_movies_df['imdb_id'] = wiki_movies_df['imdb_link'].str.extract(r'(tt\d{7})')
        wiki_movies_df.drop_duplicates(subset='imdb_id', inplace=True)
        
    except Exception as e:
        print(e)

    #  Write a list comprehension to keep the columns that don't have null values from the wiki_movies_df DataFrame.
    wiki_columns_to_keep = [column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9] 
    wiki_movies_df = wiki_movies_df[wiki_columns_to_keep]


    # Create a variable that will hold the non-null values from the “Box office” column.
    box_office = wiki_movies_df['Box office'].dropna()
    
    # Convert the box office data created in Step 8 to string values using the lambda and join functions.
    box_office[box_office.map(lambda x: type(x) != str)]

    # Write a regular expression to match the six elements of "form_one" of the box office data.
    form_one = r'\$\s*\d+\.?\d*\s*[mb]illi?on'
    
    # Write a regular expression to match the three elements of "form_two" of the box office data.
    form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+'

    # Add the parse_dollars function.
    def parse_dollars(s):
   
        if type(s) != str:
            return np.nan
    # if input is of the form $###.# million
        if re.match(r'\$\s*\d+\.?\d*\s*milli?on', s, flags=re.IGNORECASE):

        # remove dollar sign and " million"
            s = re.sub('\$|\s|[a-zA-Z]','', s)

        # convert to float and multiply by a million
            value = float(s) * 10**6

        # return value
            return value

    # if input is of the form $###.# billion
        elif re.match(r'\$\s*\d+\.?\d*\s*billi?on', s, flags=re.IGNORECASE):

        # remove dollar sign and " billion"
            s = re.sub('\$|\s|[a-zA-Z]','', s)

        # convert to float and multiply by a billion
            value = float(s) * 10**9

        # return value
            return value

    # if input is of the form $###,###,###
        elif re.match(r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)', s, flags=re.IGNORECASE):

        # remove dollar sign and commas
            s = re.sub('\$|,','', s)

        # convert to float
            value = float(s)

        # return value
            return value

    # otherwise, return NaN
        else:
            return np.nan
        
        
    # Clean the box office column in the wiki_movies_df DataFrame.
    wiki_movies_df['box_office'] =box_office.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)
    wiki_movies_df.drop('Box office', axis=1, inplace=True)

    
    # Clean the budget column in the wiki_movies_df DataFrame.
    budget = wiki_movies_df['Budget'].dropna()
    budget = budget.map(lambda x: ' '.join(x) if type(x) == list else x)
    budget = budget.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)
    wiki_movies_df['budget'] = budget.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)
    wiki_movies_df.drop('Budget', axis=1, inplace=True)

    # Clean the release date column in the wiki_movies_df DataFrame.
    release_date = wiki_movies_df['Release date'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)
    date_form_one = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s[123]\d,\s\d{4}'
    date_form_two = r'\d{4}.[01]\d.[123]\d'
    date_form_three = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}'
    date_form_four = r'\d{4}'
    wiki_movies_df['release_date'] = pd.to_datetime(release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})')[0], infer_datetime_format=True)


    # Clean the running time column in the wiki_movies_df DataFrame.
    running_time = wiki_movies_df['Running time'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)
    running_time_extract = running_time.str.extract(r'(\d+)\s*ho?u?r?s?\s*(\d*)|(\d+)\s*m')
    running_time_extract = running_time_extract.apply(lambda col: pd.to_numeric(col, errors='coerce')).fillna(0)
    wiki_movies_df['running_time'] = running_time_extract.apply(lambda row: row[0]*60 + row[1] if row[2] == 0 else row[2], axis=1)
    wiki_movies_df.drop('Running time', axis=1, inplace=True)
    
     
    # 2. Clean the Kaggle metadata.
    kaggle_metadata = kaggle_metadata[kaggle_metadata['adult'] == 'False'].drop('adult',axis='columns')
    kaggle_metadata['video'] = kaggle_metadata['video'] == 'True'
    kaggle_metadata['budget'] = kaggle_metadata['budget'].astype(int)
    kaggle_metadata['id'] = pd.to_numeric(kaggle_metadata['id'], errors='raise')
    kaggle_metadata['popularity'] = pd.to_numeric(kaggle_metadata['popularity'], errors='raise')
    kaggle_metadata['release_date'] = pd.to_datetime(kaggle_metadata['release_date'])
    
    # 3. Merged the two DataFrames into the movies DataFrame.
    movies_df = pd.merge(wiki_movies_df, kaggle_metadata, on='imdb_id', suffixes=['_wiki','_kaggle'])

    # 4. Drop unnecessary columns from the merged DataFrame.
    movies_df.drop(columns=['title_wiki','release_date_wiki','Language','Production company(s)'], inplace=True)

    # 5. Add in the function to fill in the missing Kaggle data.
    def fill_missing_kaggle_data(df, kaggle_column, wiki_column):
        df[kaggle_column] = df.apply(
            lambda row: row[wiki_column] if row[kaggle_column] == 0 else row[kaggle_column]
            , axis=1)
        df.drop(columns=wiki_column, inplace=True)
    fill_missing_kaggle_data(movies_df, 'runtime', 'running_time')
    fill_missing_kaggle_data(movies_df, 'budget_kaggle', 'budget_wiki')
    fill_missing_kaggle_data(movies_df, 'revenue', 'box_office')

    # 6. Call the function in Step 5 with the DataFrame and columns as the arguments.
    for col in movies_df.columns:
        lists_to_tuples = lambda x: tuple(x) if type(x) == list else x
        value_counts = movies_df[col].apply(lists_to_tuples).value_counts(dropna=False)
        num_values = len(value_counts)
  
        
    # 7. Filter the movies DataFrame for specific columns.
    movies_df = movies_df.loc[:, ['imdb_id','id','title_kaggle','original_title','tagline','belongs_to_collection','url','imdb_link',
                             'runtime','budget_kaggle','revenue','release_date_kaggle','popularity','vote_average','vote_count',
                             'genres','original_language','overview','spoken_languages','Country',
                             'production_companies','production_countries','Distributor',
                             'Producer(s)','Director','Starring','Cinematography','Editor(s)','Writer(s)','Composer(s)','Based on']]

    # 8. Rename the columns in the movies DataFrame.
    movies_df.rename({'id':'kaggle_id',
                 'title_kaggle':'title',
                 'url':'wikipedia_url',
                 'budget_kaggle':'budget',
                 'release_date_kaggle':'release_date',
                 'Country':'country',
                 'Distributor':'distributor',
                 'Producer(s)':'producers',
                 'Director(s)':'director',
                 'Starring':'starring',
                 'Cinematography':'cinematography',
                 'Editor(s)':'editors',
                 'Writer(s)':'writers',
                 'Composer(s)':'composers',
                 'Based on':'based_on'
                 }, axis='columns', inplace=True)

    # 9. Transform and merge the ratings DataFrame.
    pd.to_datetime(ratings['timestamp'], unit='s')
    
    rating_counts = ratings.groupby(['movieId','rating'], as_index=False).count() \
                    .rename({'userId':'count'}, axis=1) \
                    .pivot(index='movieId',columns='rating', values='count')
    rating_counts.columns = ['rating_' + str(col) for col in rating_counts.columns]
    movies_with_ratings_df = pd.merge(movies_df, rating_counts, left_on='kaggle_id', right_index=True, how='left')
    movies_with_ratings_df[rating_counts.columns] = movies_with_ratings_df[rating_counts.columns].fillna(0)
    
    db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/movie_data"
    engine = create_engine(db_string)
    
    movies_df.to_sql(name='movies', con=engine, if_exists='replace')
    rows_imported = 0
    
    start_time = time.time()
    for data in pd.read_csv(f'{file_dir}/ratings.csv', chunksize=1000000):
        print(data)
        print(f'importing rows {rows_imported} to {rows_imported + len(data)}...', end='')
        data.to_sql(name='ratings', con=engine, if_exists='append')
        rows_imported += len(data)
        # add elapsed time to final print out
        print(f'Done. {time.time() - start_time} total seconds elapsed')

In [4]:
# 10. Create the path to your file directory and variables for the three files.
file_dir = 'Files_to_ignore'
# The Wikipedia data
wiki_file = f'{file_dir}/wikipedia-movies.json'
# The Kaggle metadata
kaggle_file = f'{file_dir}/movies_metadata.csv'
# The MovieLens rating data.
ratings_file = f'{file_dir}/ratings.csv'

In [5]:
# 11. Set the three variables equal to the function created in D1.
extract_transform_load(wiki_file, kaggle_file, ratings_file)

        userId  movieId  rating   timestamp
0            1      110     1.0  1425941529
1            1      147     4.5  1425942435
2            1      858     5.0  1425941523
3            1     1221     5.0  1425941546
4            1     1246     5.0  1425941556
...        ...      ...     ...         ...
999995   10183      380     4.0   833459432
999996   10183      381     4.0   833460156
999997   10183      410     3.0   833459559
999998   10183      415     4.0   833460564
999999   10183      419     2.0   833461026

[1000000 rows x 4 columns]
importing rows 0 to 1000000...Done. 22.04093885421753 total seconds elapsed
         userId  movieId  rating   timestamp
1000000   10183      420     3.0   833459603
1000001   10183      421     3.0   833460615
1000002   10183      422     4.0   833461576
1000003   10183      433     4.0   833460968
1000004   10183      434     4.0   833459509
...         ...      ...     ...         ...
1999995   20808    69122     4.0  1258758055
1999996   20808    69640     3.0  1248641618
1999997   20808    69757     5.0  1258756389
1999998   20808    70286     4.5  1258756286
1999999   20808    71282     3.0  1258756325

[1000000 rows x 4 columns]
importing rows 1000000 to 2000000...Done. 43.88283896446228 total seconds elapsed
         userId  movieId  rating   timestamp
2000000   20808    71535     4.5  1258757070
2000001   20808    73017     4.5  1284931448
2000002   20808    74458     4.5  1284931826
2000003   20808    76251     4.0  1284931383
2000004   20808    77561     1.5  1284932264
...         ...      ...     ...         ...
2999995   31331     1485     4.0   867662780
2999996   31331     1544     5.0   867662780
2999997   31331     1573     4.0   867663188
2999998   31332      968     4.0   974205034
2999999   31332     1197     4.0   974205170

[1000000 rows x 4 columns]
importing rows 2000000 to 3000000...Done. 66.41871309280396 total seconds elapsed
         userId  movieId  rating   timestamp
3000000   31332     1210     4.0   974205261
3000001   31332     1821     3.0   974205170
3000002   31332     2782     3.0   974205034
3000003   31332     3121     3.0   974205261
3000004   31332     3249     4.0   974205034
...         ...      ...     ...         ...
3999995   41578     3175     5.0  1134007770
3999996   41578     3219     4.0  1134007516
3999997   41578     3253     4.5  1134008194
3999998   41578     3254     3.0  1134007536
3999999   41578     3300     4.0  1134007927

[1000000 rows x 4 columns]
importing rows 3000000 to 4000000...Done. 88.72915387153625 total seconds elapsed
         userId  movieId  rating   timestamp
4000000   41578     3354     4.0  1134007524
4000001   41578     3421     4.5  1134008066
4000002   41578     3526     4.0  1134008192
4000003   41578     3527     4.5  1134007752
4000004   41578     3535     3.5  1134007456
...         ...      ...     ...         ...
4999995   51433      661     5.0  1394863273
4999996   51433      783     4.0  1394863276
4999997   51433     1035     0.5  1394863180
4999998   51433     1320     5.0  1394863183
4999999   51433     1372     3.0  1394863281

[1000000 rows x 4 columns]
importing rows 4000000 to 5000000...Done. 111.04452586174011 total seconds elapsed
         userId  movieId  rating   timestamp
5000000   51433     1376     4.0  1394863191
5000001   51433     1408     5.0  1394863231
5000002   51433     1544     5.0  1394863493
5000003   51433     1590     5.0  1394863442
5000004   51433     1608     5.0  1394863433
...         ...      ...     ...         ...
5999995   61768     3317     3.5  1438075483
5999996   61768     3753     3.0  1438075487
5999997   61768     3793     4.0  1435694368
5999998   61768     3868     4.0  1438075493
5999999   61768     3869     3.5  1438075491

[1000000 rows x 4 columns]
importing rows 5000000 to 6000000...Done. 133.83629179000854 total seconds elapsed
         userId  movieId  rating   timestamp
6000000   61768     3967     4.0  1438075492
6000001   61768     3977     3.0  1435693148
6000002   61768     3986     3.0  1438075482
6000003   61768     3988     3.0  1438075496
6000004   61768     4014     3.5  1438075486
...         ...      ...     ...         ...
6999995   72206      881     3.0   859544062
6999996   72206      885     2.0   859544194
6999997   72206      891     2.0   859543674
6999998   72206      892     3.0   859544157
6999999   72206      893     3.0   859544422

[1000000 rows x 4 columns]
importing rows 6000000 to 7000000...Done. 155.68338680267334 total seconds elapsed
         userId  movieId  rating   timestamp
7000000   72206      896     5.0   859544376
7000001   72206      897     4.0   859546225
7000002   72206      898     5.0   859545331
7000003   72206      899     5.0   859545421
7000004   72206      900     5.0   859546059
...         ...      ...     ...         ...
7999995   82484     5500     3.5  1112390685
7999996   82484     5506     3.5  1112398417
7999997   82484     5522     3.0  1112399978
7999998   82484     5523     3.0  1112391906
7999999   82484     5548     3.0  1112390553

[1000000 rows x 4 columns]
importing rows 7000000 to 8000000...Done. 177.80919790267944 total seconds elapsed
         userId  movieId  rating   timestamp
8000000   82484     5553     2.5  1112397875
8000001   82484     5568     3.0  1119881317
8000002   82484     5574     3.0  1112399692
8000003   82484     5580     2.5  1112340611
8000004   82484     5621     3.0  1112390588
...         ...      ...     ...         ...
8999995   92883     1079     4.0  1125290411
8999996   92883     1084     3.5  1125291556
8999997   92883     1086     4.0  1125289812
8999998   92883     1089     3.5  1125290927
8999999   92883     1090     2.5  1125286782

[1000000 rows x 4 columns]
importing rows 8000000 to 9000000...Done. 200.1746039390564 total seconds elapsed
         userId  movieId  rating   timestamp
9000000   92883     1095     3.5  1125293103
9000001   92883     1097     4.5  1125293198
9000002   92883     1183     4.0  1125289089
9000003   92883     1193     4.0  1125289294
9000004   92883     1196     3.5  1125289630
...         ...      ...     ...         ...
9999995  103170      784     2.0  1253550718
9999996  103170      786     2.5  1253457101
9999997  103170      788     2.0  1253550486
9999998  103170      858     4.0  1253456383
9999999  103170      912     3.0  1253456512

[1000000 rows x 4 columns]
importing rows 9000000 to 10000000...Done. 222.81040287017822 total seconds elapsed
          userId  movieId  rating   timestamp
10000000  103170      924     3.0  1253455601
10000001  103170      969     3.0  1253454177
10000002  103170     1036     3.0  1253455721
10000003  103170     1089     3.0  1253455698
10000004  103170     1090     3.5  1253550730
...          ...      ...     ...         ...
10999995  113750      541     2.5  1422899953
10999996  113750      588     4.0  1484604472
10999997  113750      589     5.0  1484603764
10999998  113750      720     4.5  1422899973
10999999  113750      745     4.5  1422899397

[1000000 rows x 4 columns]
importing rows 10000000 to 11000000...Done. 245.3327977657318 total seconds elapsed
          userId  movieId  rating   timestamp
11000000  113750      904     1.0  1484603435
11000001  113750      912     2.0  1484603437
11000002  113750      919     1.5  1484603432
11000003  113750     1064     4.0  1405012121
11000004  113750     1131     4.0  1422900040
...          ...      ...     ...         ...
11999995  124380     2183     4.5  1196786159
11999996  124380     2269     2.5  1196786030
11999997  124380     2471     3.5  1196785679
11999998  124380     2571     4.5  1196787089
11999999  124380     2643     1.5  1196785847

[1000000 rows x 4 columns]
importing rows 11000000 to 12000000...Done. 267.38792085647583 total seconds elapsed
          userId  movieId  rating   timestamp
12000000  124380     2762     4.0  1196787497
12000001  124380     3000     4.5  1196787117
12000002  124380     3268     3.5  1196786272
12000003  124380     3704     3.5  1196785686
12000004  124380     4226     4.0  1196786413
...          ...      ...     ...         ...
12999995  134996    26729     4.0  1378170523
12999996  134996    30749     4.0  1378170369
12999997  134996    31410     4.0  1378170449
12999998  134996    31658     4.5  1378170312
12999999  134996    31878     4.0  1378169802

[1000000 rows x 4 columns]

importing rows 12000000 to 13000000...Done. 289.2306559085846 total seconds elapsed
          userId  movieId  rating   timestamp
13000000  134996    32587     3.0  1448423558
13000001  134996    33679     3.5  1378169508
13000002  134996    34405     4.0  1378170533
13000003  134996    36529     3.0  1398832177
13000004  134996    37729     2.5  1378169799
...          ...      ...     ...         ...
13999995  145489    59900     2.5  1230436973
13999996  145489    60037     4.0  1230262218
13999997  145489    60069     4.0  1231808198
13999998  145489    60072     1.5  1230344209
13999999  145489    60126     3.5  1230264604

[1000000 rows x 4 columns]
importing rows 13000000 to 14000000...Done. 311.62805700302124 total seconds elapsed
          userId  movieId  rating   timestamp
14000000  145489    60647     3.0  1230166514
14000001  145489    60684     4.0  1246980780
14000002  145489    60756     2.5  1230259502
14000003  145489    60939     2.5  1230724249
14000004  145489    61024     3.0  1230164356
...          ...      ...     ...         ...
14999995  156028     1791     4.0  1011742273
14999996  156028     1805     3.0  1011571988
14999997  156028     1888     3.0  1011740037
14999998  156028     1892     4.0  1011571953
14999999  156028     1894     4.0  1011740037

[1000000 rows x 4 columns]
importing rows 14000000 to 15000000...Done. 334.0987136363983 total seconds elapsed
          userId  movieId  rating   timestamp
15000000  156028     1918     3.0  1011739767
15000001  156028     1927     2.0  1011572669
15000002  156028     1937     5.0  1011571402
15000003  156028     1938     4.0  1011573995
15000004  156028     1944     5.0  1011725054
...          ...      ...     ...         ...
15999995  166559    86833     4.0  1310680935
15999996  166560       32     4.5  1232449532
15999997  166560      216     4.0  1232776592
15999998  166560      253     4.5  1232449705
15999999  166560      296     4.5  1232449370

[1000000 rows x 4 columns]
importing rows 15000000 to 16000000...Done. 356.6843328475952 total seconds elapsed
          userId  movieId  rating   timestamp
16000000  166560      344     4.0  1232776647
16000001  166560      356     4.5  1232449386
16000002  166560      593     5.0  1232448119
16000003  166560      741     4.0  1232778059
16000004  166560      784     3.0  1232776661
...          ...      ...     ...         ...
16999995  176628     7143     4.0  1437271439
16999996  176628     7362     4.5  1436671992
16999997  176628     7458     4.0  1436673533
16999998  176628     8915     4.0  1436840604
16999999  176628    26528     4.5  1436840284

[1000000 rows x 4 columns]
importing rows 16000000 to 17000000...Done. 378.7970058917999 total seconds elapsed
          userId  movieId  rating   timestamp
17000000  176628    27808     3.0  1437274867
17000001  176628    33679     4.5  1436671978
17000002  176628    37382     4.5  1436671807
17000003  176628    40629     3.0  1436840283
17000004  176628    48696     4.0  1436671710
...          ...      ...     ...         ...
17999995  186925      605     3.0   949279037
17999996  186925      608     3.0   948512227
17999997  186925      613     4.0   949278829
17999998  186925      628     4.0   948512356
17999999  186925      648     4.0   949280155

[1000000 rows x 4 columns]
importing rows 17000000 to 18000000...Done. 400.7992298603058 total seconds elapsed
          userId  movieId  rating  timestamp
18000000  186925      695     2.0  949280155
18000001  186925      708     3.0  949169240
18000002  186925      719     2.0  993444090
18000003  186925      762     1.0  949279426
18000004  186925      784     2.0  993444146
...          ...      ...     ...        ...
18999995  197286      225     4.0  862512404
18999996  197286      229     3.0  862512137
18999997  197286      230     3.0  862511452
18999998  197286      233     3.0  862512878
18999999  197286      235     3.0  862512210

[1000000 rows x 4 columns]
importing rows 18000000 to 19000000...Done. 423.20318269729614 total seconds elapsed
          userId  movieId  rating   timestamp
19000000  197286      242     4.0   862511832
19000001  197286      247     3.0   862511619
19000002  197286      249     3.0   862511772
19000003  197286      252     3.0   862513365
19000004  197286      253     4.0   862512210
...          ...      ...     ...         ...
19999995  207965     2572     3.5  1324774761
19999996  207965     3255     3.5  1324774337
19999997  207965     3755     2.5  1324774330
19999998  207965     6658     3.0  1324774501
19999999  207965    69757     4.0  1324774485

[1000000 rows x 4 columns]
importing rows 19000000 to 20000000...Done. 445.17375469207764 total seconds elapsed
          userId  movieId  rating   timestamp
20000000  207965    89864     4.0  1324774428
20000001  207966       34     5.0   916502599
20000002  207966      260     5.0   916502786
20000003  207966      509     3.0   916503034
20000004  207966      534     4.0   916502380
...          ...      ...     ...         ...
20999995  218237     3578     4.0  1462582568
20999996  218237     3681     4.0  1462583266
20999997  218237     3948     3.5  1462583079
20999998  218237     4011     3.0  1462582495
20999999  218237     4226     4.0  1462585028

[1000000 rows x 4 columns]
importing rows 20000000 to 21000000...Done. 467.03785395622253 total seconds elapsed
          userId  movieId  rating   timestamp
21000000  218237     4262     3.0  1462582989
21000001  218237     4306     3.5  1462582618
21000002  218237     4641     3.0  1462583429
21000003  218237     4855     3.0  1462582915
21000004  218237     4878     3.0  1462582599
...          ...      ...     ...         ...
21999995  228520     1291     5.0   978743987
21999996  228520     1297     4.0   978743721
21999997  228520     1304     5.0   978743987
21999998  228520     1307     4.0   978743341
21999999  228520     1313     2.0   978744714

[1000000 rows x 4 columns]
importing rows 21000000 to 22000000...Done. 489.00866770744324 total seconds elapsed
          userId  movieId  rating  timestamp
22000000  228520     1370     3.0  978744201
22000001  228520     1372     5.0  978744317
22000002  228520     1374     5.0  978744063
22000003  228520     1375     2.0  978744446
22000004  228520     1376     4.0  978744085
...          ...      ...     ...        ...
22999995  238867     3478     5.0  986684134
22999996  238867     3498     5.0  986682346
22999997  238867     3503     4.0  991536161
22999998  238867     3504     4.0  986680568
22999999  238867     3508     4.0  986682346

[1000000 rows x 4 columns]
importing rows 22000000 to 23000000...Done. 511.053484916687 total seconds elapsed
          userId  movieId  rating   timestamp
23000000  238867     3510     5.0   986683036
23000001  238867     3527     5.0   986684441
23000002  238867     3529     4.0   986682755
23000003  238867     3543     5.0  1014418597
23000004  238867     3551     5.0   986681258
...          ...      ...     ...         ...
23999995  249182    96079     3.5  1460185464
23999996  249182    96829     4.0  1461797405
23999997  249182    97304     4.0  1460346654
23999998  249182    97752     4.0  1460868550
23999999  249182    97921     3.5  1460518563

[1000000 rows x 4 columns]
importing rows 23000000 to 24000000...Done. 532.3416550159454 total seconds elapsed
          userId  movieId  rating   timestamp
24000000  249182    97923     3.5  1460518555
24000001  249182    97938     4.0  1461878500
24000002  249182    99114     3.0  1460182087
24000003  249182   102407     4.5  1460183214
24000004  249182   103042     2.5  1460184332
...          ...      ...     ...         ...
24999995  260079      537     3.0   963180727
24999996  260079      539     2.0   963106062
24999997  260079      562     2.0   970349719
24999998  260079      573     3.0   963180203
24999999  260079      574     3.0   963105272

[1000000 rows x 4 columns]
importing rows 24000000 to 25000000...Done. 554.7401037216187 total seconds elapsed
          userId  movieId  rating   timestamp
25000000  260079      585     3.0   963105510
25000001  260079      586     2.0   970354283
25000002  260079      587     3.0   970351456
25000003  260079      589     3.0   963104567
25000004  260079      590     3.0   963105135
...          ...      ...     ...         ...
25999995  270634   129011     2.0  1483987257
25999996  270634   129514     2.0  1483858904
25999997  270634   130970     2.0  1483858899
25999998  270634   132496     3.5  1483858836
25999999  270634   133201     4.0  1483942603

[1000000 rows x 4 columns]

importing rows 25000000 to 26000000...Done. 577.175993680954 total seconds elapsed
          userId  movieId  rating   timestamp
26000000  270634   133203     4.0  1483942604
26000001  270634   133205     4.0  1483942601
26000002  270634   134130     1.0  1483855797
26000003  270634   134170     5.0  1483855534
26000004  270634   134853     3.0  1483854928
...          ...      ...     ...         ...
26024284  270896    58559     5.0  1257031564
26024285  270896    60069     5.0  1257032032
26024286  270896    63082     4.5  1257031764
26024287  270896    64957     4.5  1257033990
26024288  270896    71878     2.0  1257031858

[24289 rows x 4 columns]
importing rows 26000000 to 26024289...Done. 577.7871627807617 total seconds elapsed

In [6]:
# 12. Set the DataFrames from the return statement equal to the file names in Step 11. 
wiki_movies_df = wiki_file
movies_with_ratings_df = kaggle_file
movies_df = ratings_file

In [7]:
# 13. Check the wiki_movies_df DataFrame. 
wiki_movies_df

'Files_to_ignore/wikipedia-movies.json'

In [9]:
# 14. Check the movies_with_ratings_df DataFrame.
movies_with_ratings_df

'Files_to_ignore/movies_metadata.csv'

In [ ]:
# 15. Check the movies_df DataFrame. 
movies_df.head()